# Generated by Django 5.2 on 2025-11-10 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("testApp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="title",
            field=models.CharField(default="Untitled", max_length=100),
            preserve_default=False,
        ),
    ]
