# Generated by Django 5.2 on 2025-11-14 00:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("testApp", "0003_category_remove_post_author_remove_post_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="category",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="testApp.category",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="content",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="post",
            name="name",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="post",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
