# Generated by Django 5.2 on 2025-11-14 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("testApp", "0004_alter_post_category_alter_post_content_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
