# Generated by Django 5.2 on 2025-11-14 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("testApp", "0005_alter_post_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
