# Generated by Django 5.2 on 2025-11-17 10:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("testApp", "0008_post_author"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="author",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="post",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="testApp.category",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="content",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="post",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="post",
            name="price",
            field=models.IntegerField(),
        ),
    ]
