# Generated by Django 5.2 on 2025-10-25 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="descriqtion",
            new_name="description",
        ),
    ]
